### ISSUE TITLE
Incorrect cast to IP in Network class comparisons

### ISSUE THREAD

**Issue by MuppyCwa** [tehmaze/ipcalc#47]
There is a cast to IP when comparing (e.g. `__eg__()`, `__lt__()`, etc...) in the Network class. I suspect this is a copy-n-paste error?

Anyhow, changing from `IP(other).size()` to `Network(other).size()` solved my problem when comparing instances of network classes.

BR
Markus

**Comment by tehmaze** [comment]
Fixed in 49b06692a7780ade8db987c6e4ff6902ff5db560
